export const ROUTES = {
  home: '/',
  properties: '/properties',
  property: '/properties/:id',
  model: 'model/:id',
  projects: '/projects',
  project: '/projects/:id',
  login: '/login',
  signup: '/signup',
  forgotpassword: '/forgot-password',
  resetpassword: '/reset-password',
  dashboard: '/',
  applications: '/applications',
  applicationsDetails: '/applications/:id',
  offers: '/offers',
  loans: '/loans',
  teams: '/teams',
  reports: '/reports',
  settings: '/settings',
  notifications: '/notifications',
  profile: '/profile',
  loanDetails: '/loans/:id',
  offerDetails: '/offers/:id',
  myInvestment: '/my-investment',
  appointments: '/appointments',
  transactions: '/transactions',
  transactionHistory: '/transHistory',
};

export const QUERIES = {
  LOGIN: '/auth/admin/login',
  ME: '/auth/admin/me',
  USERS: '/users',
  MERCHANTS: '/users/merchants',
  BUSINESS_lIST: '/business/list',
  PROPERTIES_LISTING: '/properties',
  PROPERTY_LISTING: '/properties/:id',
  PROJECTS_LISTING: '/projects/all',
  PROJECT_LISTING: '/projects/:id',
  PROJECTS_INVESTMENTS: '/project-investments/admin',
  ATTACH_PROJECT: '/project-investments/attach',
  PROPERTIES: '/properties',
};
